### ISSUE TITLE
Add some way to remove shot arrows

### ISSUE THREAD

**Issue by OhPointFive** [PGMDev/PGM#1027]
There should be some way to remove the arrows stuck in blocks after they've been shot. Some maps may not want players to be able to collect these arrows.

Something like
```xml
<itemremove>
  <arrow/>
</itemremove>
```
would make sense to me.

With this, #112, and if #112 respects dynamic filters, round-based maps like Sunstroke could remove all the arrows on the ground between rounds.

**Comment by calcastor** [comment]
While this could be considered part of the issue with maps like Sunstroke and Moonshine, both round-based control point maps, the more common situation in which this type of problem comes up is when players drop items like golden apples and arrows from their inventory during one round to pick up during the next. Adding them to `itemremove` is not a possibility because we want players to be able to drop the items from their inventory on these maps to give to other players and to pick up from spawners. I don't know that filters for `itemremove` could help in this situation.

**Comment by OhPointFive** [comment]
I was thinking if there were dynamic filters on itemremove, then perhaps items on the ground could all be cleared on a dynamic filter that triggered in between rounds.

Regardless though I think this would be nice as a standalone feature too, that was just an idea of where it could go in the future

**Comment by Pablete1234** [comment]
Given the nature of how specific the requested use-case is, i believe an action to kill entities that match a filter may be better suited.

`<kill-entities filter="arrows-and-items"/>`
We'll need a filter that allows checking entity type and an entity query probably (dont think those exist)
```
<any id="arrows-and-items">
  <entity>arrow<entity/>
  <entity>item<item/>
<any/>
```

This solves the issue better because it would also kill arrows which are not stuck on blocks, so if you have shot arrows into the air as the round ends they also get killed, while the itemremove proposal wouldn't

**Comment by OhPointFive** [comment]
Would this work for maps where you don't want players to be able to pick up shot arrows at all?

**Comment by Pablete1234** [comment]
It wouldn't, but:
a) have we found that to be an issue? are actual maps wanting to do that
b) if we want such a feature we could pobably just do `<arrowremove after="5s" prevent-pickup="true"/>` that specifically deletes arrows when they land on blocks after X seconds, since it's a specific enough thing that doesn't quite fit itemremove, and also prevent pickup as a whole if you want players to never pick them up

**Comment by Pablete1234** [comment]
Kill action & arrow pickup filters have implemented the functionality this issue aimed to implement
