### ISSUE TITLE
Capture Point Required Objective Not Ending Game on Latest Version of PGM

### ISSUE THREAD

**Issue by EpicPuppy613** [PGMDev/PGM#1113]
## Map:
Download: [Castle Assault.zip](https://github.com/PGMDev/PGM/files/10299480/Castle.Assault.zip)
XML: https://gist.github.com/EpicPuppy613/a8ad656d1a8a97f389843ddd6ba7d4df
*this map is currently in a development state where the capture point and monument percentages are way lower*

## Issue:
Upon capturing the capture point, the game should end according to the xml and it does in PGM version 0.13 (2bd6157), but it does not end when using PGM latest(61c13f7)

**Comment by Pablete1234** [comment]
So, this is a tricky one, but its technically working as intended.

The control point depends on stage-2, which is a filter that has not yet been completed, which means when PGM checks for "who can complete this" it finds no one, meaning it's not added to the victory conditions. "If no one can complete it, no one should be required to complete it in order to win".

You're using objective filters, which used to have issues where they would abstain before the map had loaded, that was incorrect behavior that has since been fixed, they now properly deny when asked, because the "wall" objective hasn't been broken.

Your  best option: Slap an "or" `<match-phase>idle</match-phase>`, which will make it so while loading it's considered completable

**Comment by EpicPuppy613** [comment]
So when it was working in 0.13, the objective filters abstained instead of denied and allowed the control point to be accepted as a valid objective?

**Comment by Pablete1234** [comment]
I believe so, yes
