### ISSUE TITLE
Scoreboard not rendering for post match joins

### ISSUE THREAD

**Issue by Pugzy** [PGMDev/PGM#1153]
Recent optimizations cause the scoreboard to no longer display if you join after a match has ended.

Is this the side effect of something larger or an intended change? Either way, it should still display even if you join after the match.

You can no longer join a match and quickly/easily see the status of the game (useful in many cases such as events and ranked).
Please don't tell me to use `/match` thanks.

**Comment by Pablete1234** [comment]
The root of the "issue" is purely that sidebar stops re-rendering itself after match end, which is **intended**. That new players joining are left to see nothing however, is **not** an intended change, it's just a consequence of the previous one.  The reason we want to completely disallow re-rendering after end is so that, in FFA matches, as players leave the scoreboard doesn't keep on re-rendering and re-ordering for every player that leaves, causing a ton of packets

Solution may be to have a forced-render or priority-render system similar to tablist, where after match end we can just re-render with priority for new joinees, while keeping the no-re-rendering nature.
