### ISSUE TITLE
Map voting enhancements

### ISSUE THREAD

**Issue by Pablete1234** [PGMDev/PGM#169]
- [x] Map voting should make use of a **Book GUI**, because people use chat and your voting messages move arround, can get annoying. 
- [x] **Bossbar** & cycle messages give away what the **highest** voted **map** is. May want to make it so it no longer does, so people don't vote based on that.
- [x] Try to make it more **obvious** that you can **vote for multiple maps**, several users assumed it was single vote even if the messages are layed out as a list with a corss or check each.
 - [x] Add a **flag** to **/pool** that shows **map scores**, to see how they evolve
 - [x] Consider tweaking/**adjusting map scoring** if it's not being too representative of the playerbase
 - [x] Consider more **mechanisms to pick the voting maps**, like gamemode rotation based approach. Decreasing map chance based on other selected maps of the same type in the same vote adds variety.
 - [x] Playercount-based picking. One large pool is created and maps selected for voting depend on current playercount.

**Comment by Xerocoles** [comment]
At OCC it might not matter as much for gamemode variation, although they can speak for themselves, but at Stratus it's super important that we get different pools of maps for each gamemode, and so we can choose the gamemode flow ordering.  Otherwise it's gonna be really unbalanced and conquest will hardly _ever_ play, just as an example.  So yeah, although we aren't sure if we want votations yet, gamemode pools is a must for us, and I'm guessing it would still benefit OCC.

**Comment by rafibaum** [comment]
@Pablete1234 I think this should be closed unless can flesh out an actual concept for an extension to map voting.

**Comment by Pablete1234** [comment]
@rafibaum There is one, just kind of abandoned.

The idea behind it is that the weight of maps is able to be influenced by current playerbase and by other selected maps in the same vote. That means the more tags of a certain type you share with the already picked maps, the lower weight the map will have. It will make it so less maps of the same type will be on the vote.

**Comment by rafibaum** [comment]
You can either update the issue title/description to reflect that concept then or just close this and make a new issue.

**Comment by Pablete1234** [comment]
Finished in #1010
