### ISSUE TITLE
Multiple winner support in FFA tie

### ISSUE THREAD

**Issue by Xerocoles** [PGMDev/PGM#195]
When people tie in FFA (or any gamemode? not sure if it's only ffa or not) it says "Game Over!" instead of "Xerocoles and Notch wins!" for example, like it used to say.

**Comment by KingOfSquares** [comment]
This is because of this: https://github.com/Electroid/PGM/blob/7f599daf64320c401ba7c5c5108dbaf22fb4c5e6/core/src/main/java/tc/oc/pgm/listeners/MatchAnnouncer.java#L71

`getWinner` will return `null` if there are more than 1 winner https://github.com/Electroid/PGM/blob/7f599daf64320c401ba7c5c5108dbaf22fb4c5e6/core/src/main/java/tc/oc/pgm/api/match/event/MatchFinishEvent.java#L37-L43

Instead `getWinners` should be used and if it returns multiple `Competitor`s it should display all those as winners.

"Game Over!" Should still be used if there are no winners for some reason. (if `getWinners = null`)

**Comment by Pablete1234** [comment]
You can look at the 1.9+ PGM source to see how it was implemented. But essentially, you need to be able to return more than one winner as a result of match end

**Comment by KingOfSquares** [comment]
> You can look at the 1.9+ PGM source to see how it was implemented. But essentially, you need to be able to return more than one winner as a result of match end

I've looked at it now. But unsure how it displayed them. https://github.com/OvercastNetwork/ProjectAres/blob/079d13ce62aee9a85f6871384a53356bd25735a8/PGM/src/main/java/tc/oc/pgm/listeners/MatchAnnouncer.java#L83-L87

Does this display multiple winners as `Winner, Winner2` or `Winner and Winner2`
And do i also make it do something like this https://github.com/OvercastNetwork/ProjectAres/blob/079d13ce62aee9a85f6871384a53356bd25735a8/PGM/src/main/java/tc/oc/pgm/listeners/MatchAnnouncer.java#L88-L90

Whenever there is more than 2 winners?

**Comment by Pablete1234** [comment]
It displays using a `ListComponents` wich renders as `Components#naturalList`, wich will become, depending on number of elements:
 - 0 : blank component ``
 - 1: the same element `Player1`
 - 2: a "pair" of elements: `Player1 and Player2`
 - other: iterate concatenating with `,` and with `, and`: `Player1, Player2, and Player3`

https://github.com/OvercastNetwork/ProjectAres/blob/master/Util/core/src/main/java/tc/oc/commons/core/chat/Components.java#L491

It only displays the winners in the title if there's up to 3. More of them would be hard to fit so they only display in chat and the match over message is a generic `X winners!`
