### ISSUE TITLE
Remote map sources

### ISSUE THREAD

**Issue by Electroid** [PGMDev/PGM#4]
Right now a `MapSource` is required to be a `File` on the local filesystem. We want to allow PGM to load maps from `Github` (more important) or `Dropbox`. 

Two important considerations in the design.
1. Map loading and XML parsing should be done asynchronously on server startup. Meaning, that server startup should block until at least 1 map is loaded, the rest are parsed on a different thread(s).

2. PGM should **not** download the *entire* `Github` or `Dropbox` repository, it should use their APIs to only load maps when requested (eg. load all the maps on rotation, search and load for a map when it sets next)

**Comment by Pablete1234** [comment]
I don't think loading maps on demand is the best idea. You're gonna need to parse the XMLs to know what maps are available, and having to download the maps individually on cycle doesn't seem like that great of an idea. Also, instead of focusing on github, git repositories as a whole could be used. Cardinal did this where server startup or /newmaps command, would fetch the git repo, wich will be using git hence only downloading changes since last pull, making the diffs relatively small.

**Comment by Electroid** [comment]
Now should be easy to add a new `MapSourceFactory` / `MapSource`

**Comment by rafibaum** [comment]
@KingOfSquares you're working on this right?

**Comment by KingOfSquares** [comment]
Correct. Currently doing some research on git possibilities on popular
server providers. I have a version with JGit running, but electroid told me
he wanted to not import in JGit.

**Comment by KingOfSquares** [comment]
This should be closed! @rafibaum
