### ISSUE TITLE
Observers can't view villager trades

### ISSUE THREAD

**Issue by MarcRoizman** [PGMDev/PGM#571]
Clicking on a villager while in observers opens an empty chest GUI rather than the trading options.

**Comment by ghost** [comment]
I could not fix this issue but I investigated a bit and I discovered that villagers.getInventory returns an InventorySubcontainer instead of InventoryMerchant, causing Bukkit.getInventory to get the wrong type.

https://github.com/PGMDev/PGM/blob/70c139f3094195b68477180bce7ab645a9e6267b/core/src/main/java/tc/oc/pgm/inventory/ViewInventoryMatchModule.java#L155
