### ISSUE TITLE
maps-default gets downloaded and used even when disabled

### ISSUE THREAD

**Issue by Brottweiler** [PGMDev/PGM#574]
Even if one would disable the `maps-default` in the PGM config, PGM will still autodownload it and look for maps in there. This can be worked around by replacing the `PGMDev/maps` repo in the config with an empty repo (a repo that doesn't exist).

**Comment by applenick** [comment]
I just did some experimenting and believe I found the source of the issue. 

So when the `repositories:` is blank as recommended to disable git support, `reloadConfig()` appears to be populating the [`getMapList(...)`](https://github.com/PGMDev/PGM/blob/dev/core/src/main/java/tc/oc/pgm/PGMConfig.java#L124) call with the default [config.yml](https://github.com/PGMDev/PGM/blob/dev/core/src/main/resources/config.yml#L29) instead of the user defined one.

The change needed to resolve this would be to switch the default config.yml `repositories:`  to be commented out (see Suggested Change). So the user can add it if they like. 

However I don’t believe this alone is the best user experience, so perhaps an additional check could be added in `PGMConfig` that’s run after the folders & repos are checked and if everything is empty, then downloads the default repo. 

Let me know if there’s any objections to these changes and if not I can open a PR later with them.

## Suggested Change 
```
  repositories:
    # List of git repositories to load maps.
    #
    #  - uri: "https://<user>:<oauth-token>@github.com/myUser/myPrivateRepo"
    #    path: "maps"
    #    branch: "master"
    #    folders:
    #    - "tournament"
    #
    # To enable the default maps, uncomment the repository below.
    # - uri: "https://github.com/PGMDev/Maps"
    #  path: "maps-default"
```
