### ISSUE TITLE
1.7 players don't get forced to obs in Blitz after death

### ISSUE THREAD

**Issue by alejopca** [PGMDev/PGM#651]
When a player playing in 1.7.X is playing a blitz match and they die they aren't being force to observers, while any player on every other version is. 
evidence: https://youtu.be/Zfj-irBrWLM

**Comment by alejopca** [comment]
With poshengineer we found out it only happens when it is a void death https://youtu.be/k2fS3rXzsNM we did a cannon duel and when I blew him he went to obs

**Comment by KingOfSquares** [comment]
Void deaths also dont register some stuff in stats for the killing player.
Maybe it does not trigger a MatchPlayerDeathEvent?

**Comment by ghost** [comment]
This happens because of how legacy players' deaths are handled. What happens here is that when a legacy player falls into the void and die they're forced into adventure mode instead of creative in order to fix a fly bug. This causes PGM not to force players to observers because it sees them as failings and when they try to change teams they get a warning that reads "You are in too much danger to leave the match right now".
