### ISSUE TITLE
Tab completion not working in map commands

### ISSUE THREAD

**Issue by ChemistryX** [PGMDev/PGM#66]

**Comment by Electroid** [comment]
Still an issue?

**Comment by Brottweiler** [comment]
Yes.

**Comment by Pugzy** [comment]
I have attempted to make the changes to allow this on my branch https://github.com/Pugzy/PGM/commit/ae6d1708de563eaf93885905a3ac5075fcd67b51.

Using the same fancy hyphen character as OCN did to replace spaces.

![image](https://user-images.githubusercontent.com/8608892/69014655-6dc23a80-0984-11ea-96f0-399f9e1f1684.png)

Does anyone recall what OCN would do when tab completing something such as `The Ni` [tab] ... le.
Once I have added the space results are no longer suggested as it is a different argument.

**Comment by Pablete1234** [comment]
If you t ried to tab-in `A Ne` it would tab-in as `A New┈Day`, the vanilla mc client won't replace text already added by the user, and that includes the space, wich will be left unmodified. The issue is, intake will likely not handle this very well had similar issues with map tags where only the first tag will auto-complete, anything after the first space never gets thru any `getSuggestions`

**Comment by rafibaum** [comment]
@Pugzy How far did you get with this?

**Comment by Pugzy** [comment]
@rafibaum got some of it working on https://github.com/Pugzy/PGM/commit/ae6d1708de563eaf93885905a3ac5075fcd67b51 ran into the issue above described by Pablo.
