### ISSUE TITLE
Feature: Map History & Play Count (for map creators)

### ISSUE THREAD

**Issue by technodono** [PGMDev/PGM#687]
This is suggestion to add 2 new features to PGM called map play count and map history

### Map play count

This would show people how many times a map has been played overall.

This feature would be useful to map creators who want to know how popular their maps are or to anyone wanting to know this information

This statistic would be split up into 5 sub-categories

_**Vote count:** How many times the map has appeared in the vote book_

_**Play count:** How may times a map has actually been played_

_**Play%:** How many times this map has been played per-pool as a average % against other maps_

_**Popularity:** **play%** displayed as a rank (e.g. Ranked No.1)_

_**No.Play%:** just a number showing how many times a map is played per day as an average_

### Map History

This feature would keep of the maps that were played in ordered from most recent to oldest. Useful to know what maps were played when and how often pools/maps appear on the server

**Comment by applenick** [comment]
If it’s okay I’d like to assign this issue to myself. 
I’m not sure what the general consensus is on including stats like this directly into PGM (based on previous features, it may be out of scope), but I definitely see this working well as a stand alone plugin (open sourced) which hooks into PGM.

I’ll be experimenting with that and leave some progress updates here.  

Update: After doing a little research into this issue and receiving some advice from @Pablete1234, deciding against working on this for now. I unassigned myself in case anyone was interested, but just a friendly warning the issue of tracking map stats is a lot more complicated when you get into it. Maybe in the future we can work on a solution that solves this issue. But atm, not as much of a priority.

**Comment by KingOfSquares** [comment]
Cool feature idea, not a PGM responsibility though imo

**Comment by Pablete1234** [comment]
Going to close this one for now as it probably is out of scope for pgm, and it would *not* be an easy one to implement in a way that is easily explorable without misleading data. 

The user may assume independence between the variables when they're actually related in ways that may not be expected or understood by players, some examples: 
 - A map that is very liked will appear less often in the vote (since it getting voted and played makes it not appear again)
 - A map that is very disliked will appear less often in the vote (since it getting a bad rating makes it not appear again)
 - A map that consistently gets 2nd place will be the one to appear the most in the vote, however, it will not be the most played
