### ISSUE TITLE
Observer Tools not working on specific maps

### ISSUE THREAD

**Issue by applenick** [PGMDev/PGM#726]
# Observer Tools not working on specific maps

It was brought to my attention by Darkrowo, that on certain maps the observer tools are not working. I attempted to debug this and came up with nothing as to why it would not be working. Basically when clicking any of the tools, the `onInventoryClick` method is just not being called only on these maps.

The maps we’ve found this issue on
- Tetrad
- Golden Drought

There may be additional, and I’ll update this list if others are found.

## Video
https://youtu.be/R7GlxdvC6xo

Any ideas on how to fix this would be appreciated!

**Comment by KingOfSquares** [comment]
This might also explain why the stat thing also does not work sometimes

**Comment by Pablete1234** [comment]
Check if such maps have observer-specific kits, they may be changing something there that could cause this

**Comment by applenick** [comment]
@Pablete1234 Golden Drought does not give any observer-specific kit. However Tetrad does give Night Vision.

**Comment by Pugzy** [comment]
I have had a look into this and found something interesting
When it doesn't work the item lore inside the `clicked` shows as `§k§0§k§3§1§k§0§k§7Current Speed: §eNormal` when it should be 
`§7Current Speed: §eNormal` so the equals check fails and the item click does nothing

This is because maps with `item-mods` module checks on inventory open: https://github.com/PGMDev/PGM/blob/66455cd9339204a2ec57adeb01520338b0b5fcc1/core/src/main/java/tc/oc/pgm/itemmeta/ItemModifyMatchModule.java#L55

This sets the `APPLIED` meta on every item to mark it as checked (any mods applied) 
https://github.com/PGMDev/PGM/blob/66455cd9339204a2ec57adeb01520338b0b5fcc1/core/src/main/java/tc/oc/pgm/itemmeta/ItemModifyModule.java#L34

This meta is set using the `LegacyItemTag` which modifies the lore with extra color codes https://github.com/PGMDev/PGM/blob/66455cd9339204a2ec57adeb01520338b0b5fcc1/util/src/main/java/tc/oc/pgm/util/inventory/tag/LegacyItemTag.java#L70 (read class docs at top of class to see how this works)

So the produced inventory has messed up color codes for item lore but the version the equals checked against does not.
