### ISSUE TITLE
Fall through block when placing outside the map.

### ISSUE THREAD

**Issue by JesperSvensson00** [PGMDev/PGM#783]
This example occurs often when you bridge. Furthermore some maps have poor level design and have spots where you don't expect it to be void region.

Steps to reproduce:
1. Sneak on the edge of a block so you are outside the allowed region.
2. Press 'S' / walk backwards
3. Place a new block beneath you

The block will appear long enough for you to leave the block you were standing on. Then it will disappear since you are not allowed to build outside the region. The problem is since you are not standing on any block now you will fall through.

Possible fix:
Try detecting this particularly case and tp the player back to the block.

**Comment by Pablete1234** [comment]
The "block appears for long enough" because of the client-server desync from when you place the block (client side) to when the server tells you the block placement isn't valid. I don't think pgm should teleport arround players who try to place blocks in invalid regions, being teleported arround (when you sometimes wouldn't fall) would create terrible user experience.

I'm open for discussion but i don't think there's any good solution to this other than players learning the maps and the maps being a bit more intuitive about where you can and can't build, but that's not an issue on PGM itself

**Comment by RuedigerLP** [comment]
PGM client 👀

**Comment by JesperSvensson00** [comment]
> I don't think pgm should teleport arround players

Yeah you are right. I thought I mention it if there was a "easy" fix or if someone else comes up with an idea.
