### ISSUE TITLE
Maintain a player's nametag when they pick up a flag

### ISSUE THREAD

**Issue by lefckntea** [PGMDev/PGM#811]
When a player picks up a flag their nametag just disappears. It seems rather odd and you can't seem them through walls like usual  (if you're in a building for example and the beam isn't visible)

**Comment by Pablete1234** [comment]
Could you provide screenshots of this? What client version are you looking at this on? Does it have something do with legacy flag beams?

**Comment by lefckntea** [comment]
![image](https://user-images.githubusercontent.com/39029307/108237440-31adf480-7148-11eb-870a-313334c71ab5.png)
1.7

**Comment by Pablete1234** [comment]
So it looks like legacy flag beams work by making a zombie ride the actual player, causing it to remove the nametag, as well as preventing the player being hit from above.

The solution would be to simply not mount the zombie flag onto the player itself, and simply move it arround by replicating the players' movement packets on the entity itself.
To prevent clients from seeing the beam falling, 1.7 clients should use invisible wither skulls as the rider, and 1.8+ players should get the bottom zombie to have NO_AI flag. Alternatively could try to make it armor stands, which older clients should still see as zombies, but newer clients can have them set to marker=true for no hitbox.

The reason 1.8+ clients are a concern is because PGM does have a setting to enable legacy flag beams for all clients.

I'd be glad to review a PR to upstream with changes to make this happen
