### ISSUE TITLE
Team Switch Kit does not trigger Blitz end condition

### ISSUE THREAD

**Issue by TBG1000** [PGMDev/PGM#960]
An old "Include" file, called `infection.xml` (which can be found [here](https://github.com/OvercastNetwork/maps.oc.tc/blob/master/Include/infection.xml)) uses the Blitz module and the [Team Switch kit](https://pgm.dev/docs/modules/gear/kits/#team-switch-kit) for the Infection gamemode. 

However, in 1.8 PGM, the team switch kit appears to interfere with Blitz, causing the game not to end when all "Humans" in a match are killed (and thus switched to the "Infected" team). Examples of this behavior can be seen [here](https://youtu.be/i2mq6cZxN9Q) (starting a match while alone) and [here](https://www.youtube.com/watch?v=fEs6QF36g-M) (one player on Infected, one on Humans). Expected behavior is for the match to automatically end when all human players are infected. Workarounds for this problem include using an invisible hill that will be captured by the infected once no humans are left.

More information or discussion on this bug can be found at `#maps`, PGM Discord.

**Comment by Pugzy** [comment]
Implemented this locally like such https://github.com/Pugzy/PGM/commit/eeb916a515cc9b3f8e8b26b61b97195466ca3af9 which seems to work I can make a PR following the below query. 

[OCN Project Ares](https://github.com/OvercastNetwork/ProjectAres/blob/master/PGM/src/main/java/tc/oc/pgm/blitz/BlitzMatchModule.java#L199) did a strange check on all potential dead players inside an immutable set but I'm not too sure why . Any ideas anyone?

**Comment by Pablete1234** [comment]
> [OCN Project Ares](https://github.com/OvercastNetwork/ProjectAres/blob/master/PGM/src/main/java/tc/oc/pgm/blitz/BlitzMatchModule.java#L199) did a strange check on all potential dead players inside an immutable set but I'm not too sure why . Any ideas anyone?

@Pugzy 
The reason for it is that setPlayerParty will Match#getParticipants, meaning that if you don't create a copy it will cause a concurrent modification exception, for iterating and removing at the same time

What the code *actually* does is:
For each player in the match, if they died, move to obs, then re-compute what team is winning.
The reason to do it this way instead of processing each death one by one, is that if the last two players die on the same tick, that logic will end as a tie while the current would arbitrarily give the win to one or the other
