### ISSUE TITLE
Implement contested-decay attribute for control points

### ISSUE THREAD

**Issue by lefckntea** [PGMDev/PGM#976]
If i have decay on a hill, it decays once "nobody dominates" the hill (documentation)
There should be a difference between the that state where no one is on the hill and where both/multiple teams are on the point because gameplay wise they're very different and it wouldnt make sense for the hill to decay when it's contested.

See my map Sunstroke played in last conquest tournament 
if it's somehow possible with pgm magic then sure let me knowbut the xml is probably already hacky enough

**Comment by lefckntea** [comment]
add like a decay-rule similar to capture-rule idk man

**Comment by Pablete1234** [comment]
My proposal is to add `contested-rate` which defaults to `decay-rate` (for backwards compatibility reasons), and is used whenever the point is not being dominated by a particular team, but is being contested by multiple teams.

At the moment a control point goes at different rates if:
 - A team is capturing (normal rate), eg: Neutral -> Captured
 - A team is restoring their ownership (at recovery-rate), eg: Owned (50% neutral) -> Owned
 - Naturally restoring ownership (at decay-rate), eg: Owned (50% neutral) -> Owned
 - Decaying towards neutral cause no one is on the point (at owned-decay-rate), eg: Owned -> Neutral
 
 The main difference between recovery-rate and decay-rate is simply that the former occurs when a team dominates (they have the players on point) while the later occurs when no team dominates, it be either because no one is on the point, or because capture-rule says no one dominates (eg, exclusive rule and multiple teams, or no team has a majority or a lead).
 
 This `contested-rate` would fill the gap of further separating decaying because no one is on point, vs decaying because there's a conflict between multiple teams capturing (respecting the exclusive/majority/lead rules)
