### ISSUE TITLE
Implement assists

### ISSUE THREAD

**Issue by lefckntea** [PGMDev/PGM#998]
If you've damaged a player for some x damage (or percentage) in the last x seconds and then they die it counts as an assist.
not sure about the exact values
in chat it will display "teaFYI was shot by AdamChen +1"
the value at the end for how many people assisted that kill
then in the stats menu it shows how many assists you had 

`test`

**Comment by Pablete1234** [comment]
@Pugzy and I already visited this topic a while ago, and there's a mostly-working implementation of it.

There's a damage-queue that stores who is responsible for the damage you've taken, and pulls out of the queue as you heal those hearts, so as an example:
 - You start at 10 hearts 
 - Player A deals 7 hearts (current: 3)
 - You regenerate 3 hearts (current: 6)
 - Player B deals 5 hearts (current: 1)
 - You regenerate 1 heart (current: 2)
 - Player C deals 2 hearts (you died)

This would award player C the kill (last hit), and the assists would be 20% for player C, 50% for player B, and 30% for player A.

Time is not involved at all in this, because it's a matter of if you were able to heal the damage dealt or not. If you healed it: it doesn't count as an assist, if you didn't heal it: it does count.

The main point of discussion is how to exactly display this on chat (if at all), and what other uses it can give (mainly, offering alternative to kill rewards where you may get the kill-reward as long as you get a certain % of the kill, configured in xml).

My personal proposal as to what we should do for death messages, is show the % you contributed to the kill when you have been involved, and they should show in bold (as in: you were involved) instead of it being "you got the final blow", something like:

"PlayerA was slain by PlayerB's Stone Sword (35%)" (you are player C, not in the death message yourself)
I'm not sure if we should really show assists on *all* death messages, as it may pollute the chat and make it harder to read, we could show the players who were involved as a tool-tip when you hover on the death message, eg: "Player A (35%), Player B (75%)"

**Comment by lefckntea** [comment]
ok the damage queue thing is actually really good for this
i think for death messages any way other than what i proposed will look cluttered.
i would add a +1, +2 etc. for how many other people assisted that kill. you can make it bold if you're included.
if you hover the death messag with your cursor it'll show details like every player & their percentage

why i don't think it should be the way you suggested its quite confusing. it seems like the percentage has something to do with the kill but it doesn't look like it's you who contributed that much damage. i got confused when i read it atleast.

**Comment by Pablete1234** [comment]
This was already merged
